### ISSUE TITLE
Run --user and --group-add aren't working

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rio#63]
Steps for --user:
1.  rio run -n tsk1/tuser --user demo-user nginx
2. rio kubectl get -n <namespace> -o=json deploy/tuser

Results:
No user is set in k8s

Steps for --group-add
1.  rio run -n tsk1/tgradd --group-add demo-group nginx
2.  rio inspect tsk1/tgradd

Results:
No group is set on rio side and is not being passed to k8s

**Comment by StrongMonkey** [comment]
@tfiduccia the syntax has changed a lot. I did a bit research and k8s takes UID and GID instead of name to poplate its securityContext. So if you do `rio run -n tsk1/tuser --user 10 nginx` and `rio exec tsk1/tuser id` that should give you the current uid. There is no mapping for grouping right now. Going to talk to darren about it.

**Comment by StrongMonkey** [comment]
We are going to change the mapping so that `--user` and `--group` only takes integer and they are mapped to `UID` AND `GID`

**Comment by tfiduccia** [comment]
Version - v0.1.1-rc1
Mapping only takes integers
