### ISSUE TITLE
Test github workflow

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rio#660]
We need to test github workflow. This is done by adding github token to rio. Once token is added, rio will use github webhook to watch push and tag events and creates new services.

We need to test the following scenario: 
1. Rio is able to configure github webhook to github repository.
2. Push and PR event can trigger rio to create a new service.
3. User is able to see deployment status in Github.

**Comment by StrongMonkey** [comment]
@rancher-max don't start testing this until alpha3 is out.

**Comment by rancher-max** [comment]
I used an access token that has all permissions, and by default the webhook rio created is watching `Branch or Tag Creation` and `Pushes`. I believe it should watch `PR` as well by default? When I add that manually to the webhook and create a PR, the deliver fails with response: `{"code":451,"message":"pull request is not enabled","type":"error"}`

Steps I took:
1. `rio secret add --github-webhook` --> keep default namespace and paste my gh access token
2. `rio run -p 8080 -n ghook https://github.com/rancher-max/rio-demo`
3. Validated the webhook created in Github (success, but maybe without all the proper default selections)
4. Create a few changes in master, with PRs and directly committing. In Github, the `Environments` section now looks like this, with everything stuck in Pending even after successful builds:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/55997940/68327748-2b972000-008b-11ea-99ce-a7b6a2f9d139.png">
rio built successfully and updated the service.
5. Added `Pull Requests` to the webhook and submitted a PR. This triggered the hook, but it failed with the error described above.

So overall, I'd say 2 issues with this:
1. PR hooks don't work.
2. User is unable to see deployment statuses in Github.

**Comment by rancher-max** [comment]
Some of that was my fault. This technically fixes both the issues when running with the proper flags: `rio run --build-pr -n gh -p 8080 --template https://github.com/rancher-max/rio-demo`

The only tag that isn't necessary in this example is the `-n` flag for the name. Now this works on PRs and the user is able to see the deployment statuses and endpoints in Github. 

However, it doesn't apply versions, and instead overwrites the service and rolls out weight, which doesn't mean much since they both have the same endpoint now:
```
NAME      IMAGE                                  ENDPOINT                                         PORTS     SCALE     WEIGHT    CREATED              DETAIL
gh        default-gh-n5nqn-ccd1159-pr12:c21d5    https://gh-v0-default.k6yhek.on-rio.io:32754     8080      1         35%       About a minute ago   
gh        default-gh-n5nqn-ccd1159-0995c:76888   https://gh-v0-default.k6yhek.on-rio.io:32754     8080      1         65%       5 minutes ago        
```

`kubectl get rs` shows the different resources, and `rio pods` shows all of the running pods on the services.

I believe this should be fixed by changing the behavior of the `--template` flag to act like `rio stage` and not automatically rollout. Something also needs to be fixed to apply versions properly in rio to these services so that the "staging" deployment does not overwrite the "production" one.

**Comment by StrongMonkey** [comment]
@rancher-max @izaac available to test in alpha4.

**Comment by rancher-max** [comment]
@StrongMonkey This is okay... but I don't like the flow in current state. For what it would be used for, I don't think it is working properly.

I created a template, then submitted a PR to my GH repo: https://github.com/rancher-max/rio-demo/pull/14/files

This created a deployment to `staging` in Github:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/55997940/68607613-3af0e180-046e-11ea-80f9-2d5ba4c94e0e.png">

However, since `--template` in rio automatically transitions new versions to be the promoted version, which causes that "staged" version to be the "rio production" endpoint.

**Comment by rancher-max** [comment]
Above issue created to track the odd behavior. GH workflow otherwise is working
