### ISSUE TITLE
instructions for using CNAME will not work as written

### ISSUE THREAD

**Issue by oskapt** [rancher/rio#973]
In section 1a of [the documentation](https://github.com/rancher/rio/blob/master/docs/publicdomain-external-services.md) we instruct the user to point `myproduction.com` to the `on-rio.io` domain with a CNAME.

It is not possible to use a CNAME at the root of a domain. They could use a CNAME for `www.myproduction.com` but they will not be able to point the root of the domain to a Rio domain. 

The obvious solution, then, is to create an A record.

The instructions to use the IP are only provided for situations where RDNS was not enabled within Rio, but they also tell the user to point to the host where the API gateway is listening, which sounds like it will pick the IP for the one host currently hosting the LoadBalancer service. What happens if that host goes away?

**Comment by vincent99** [comment]
Most DNS providers have a fake kind of record (e.g. "ALIAS" in AWS) or pretend to let you put in a CNAME but "flatten" it (e.g. CloudFlare) to solve this.

They resolve the name you give periodically and return the corresponding A record responses so that it acts like a CNAME without actually being one.

If your provider doesn't, then you have 3 choices:

- Get a better provider.

- Don't use the apex (some providers also offer a fake "redirect" record that resolves to their IP and returns a 301/2, which works if you want to be able to hit both names but are happy with ending up on `www`).

- Maintain a record with the right IPs in it as nodes come and go, on your own, manually (or script it, or use floating IPs that never change).  This is the same situation as having disabled RDNS.  Nothing is "picking" the right IPs for you automatically.

**Comment by oskapt** [comment]
Technically, no one should be running their website on the root of their domain. It should always be on a host within the domain, but that's not the world we live in. Even Rancher doesn't do it.

It is not possible to use an alias to a record in another zone, only to a record in the current zone, and only if that record is not also a CNAME. Thus, even pointing `www.rancher.com` to `foo.bar.on-rio.io` and then trying to point `rancher.com` as an alias for `www.rancher.com` will fail. This is not a situation where one needs a better provider - it's how DNS works.

A redirect from the apex would work, but people are not going to jump through a whole bunch of hoops and hacks just to use Rio.

If we're going to tell our users to go "write a script to track your Rio IP and update it when it changes," they're just not going to use Rio. 

Architecture discussions aside, the documentation is still wrong. You cannot point "myproduction.com" as a CNAME to anything.

**Comment by davidnuzik** [comment]
Documentation has been fixed now. We also had a discussion on how we might be able to tackle this but the ideas we had were not very realistic. Please let me know if you'd like to discuss further / re-open the issue.
